### ISSUE TITLE
New pull request failed

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/legacy-templates#114]
Hi, My new pull request failed but the error seems irrelevant to my changes. Please help look into it.

![image](https://user-images.githubusercontent.com/47135828/113648293-f8f9b880-96be-11eb-8041-993fe430b8d5.png)

![image](https://user-images.githubusercontent.com/47135828/113648226-d8c9f980-96be-11eb-9caf-54c4a80cff04.png)

Thanks,
Zehe

**Comment by Nebulis** [comment]
Should be fixed, try to rebase or merge
