### ISSUE TITLE
legacy project could not start up

### ISSUE THREAD

**Issue by chongsoon** [OpenCerts/legacy-templates#14]
Hi, 

I tried to start the project in my local environment. It shows a blank page. 

I have tried rebuilding and to no avail.

I tried starting up NUS branch and I could see the main page.

Please advise.

**Comment by chongsoon** [comment]
Is anyone able to advise or assist?

**Comment by nikhilranosys** [comment]
There is a test file which calls the localhost:3000. See: https://docs.opencerts.io/document_renderer.html#testing-using-the-indexhtml-file

**Comment by rjchow** [comment]
thanks for the response nikhil!
chongsoon I've updated the readme, please let me know if you still have any queries
https://github.com/OpenCerts/legacy-templates#development

**Comment by chongsoon** [comment]
thank you both for your responses, the readme definitely helps. one last question, for going to production for legacy viewer, do we host our own or would it be hosted by govtech?

**Comment by rjchow** [comment]
legacy renderer continues to be hosted by govtech indefinitely, so make your PRs to this repo

**Comment by chongsoon** [comment]
ok thanks
