### ISSUE TITLE
integration test failed locally

### ISSUE THREAD

**Issue by mmysgp** [OpenCerts/legacy-templates#15]
> npm run integration:headless

Integration test failed when running locally.
All NP's templates passed the integration test in Apr when we did the last modification in opencerts-website. Now using legacy template, some succeeded, some failed, even through we did not change any thing. 
![image](https://user-images.githubusercontent.com/36496605/63338929-6041e800-c376-11e9-9a1e-66b24c5e93e7.png)

Another error encountered:
![image](https://user-images.githubusercontent.com/36496605/63339056-a008cf80-c376-11e9-88bc-4c16da734b8d.png)

Even GovTech's template also failed.
![image](https://user-images.githubusercontent.com/36496605/63339086-b878ea00-c376-11e9-8140-d6a273da7bf8.png)

How do we know whether the code is good to submit a pull request? Please try out the integration test locally and let us know how to proceed.

Thanks.

**Comment by rjchow** [comment]
will look at this thanks

**Comment by rjchow** [comment]
I'm not having trouble executing the integration tests locally or on the travis environment, so lets troubleshoot your environment

- clear out your node_modules folder and run npm install
- have to run `npm run start` inside legacy-templates before running integration tests

**Comment by mmysgp** [comment]
tried to reinstall legacy template on my PC. All NP's templates passed the integration test.
But other institute's templates still got error. Is it related to the PC specs?

![image](https://user-images.githubusercontent.com/36496605/63401286-56b59000-c409-11e9-9be0-ad495dba3dad.png)

![image](https://user-images.githubusercontent.com/36496605/63401255-38e82b00-c409-11e9-990d-68abd7f0536d.png)

**Comment by rjchow** [comment]
possible but I suspect quite unlikely as the travis environments are quite low spec
are the failures consistent between runs?

**Comment by mmysgp** [comment]
I tried on Mac, no error.
But on my PC (Windows 10), the error is consistent between runs.

Btw, may I know the URL of the legacy template (Both Testing and PRD) so that we can use it to develop a preview function in our system?

**Comment by rjchow** [comment]
hmm maybe its a unix thing I'll have a look at that when I have access to a windows environment
legacy template renderer is hosted at https://legacy.opencerts.io/ , there's no testing preview as there is no verification of the certificate done by the renderer (i.e it works for both testing and prod certs)

**Comment by mmysgp** [comment]
The two new templates also failed integration test in travis. 
![image](https://user-images.githubusercontent.com/36496605/63580830-37b12c80-c5c8-11e9-8e0b-f14ac0800dee.png)

However, they can be rendered successfully locally.
![image](https://user-images.githubusercontent.com/36496605/63580946-734bf680-c5c8-11e9-9939-73e9bca8d340.png)

Please check the Pull Request #22 for details.

**Comment by mmysgp** [comment]
Solved the integration test issue for two new NP templates after using signed JSON files.
However, still encountered error for other institution's templates when running locally.

**Comment by rjchow** [comment]
thanks wu yong
