### ISSUE TITLE
How to go to production

### ISSUE THREAD

**Issue by nikhilranosys** [OpenCerts/legacy-templates#17]
I have generated pull request for SMU templates and our team will proceed with the testing now using netlify link in test file. Is this the correct way of testing the templates before pull request review?

After we are done with testing and OpenCerts team merge it, will we be able to verify our certificates directly on https://opencerts.io ? or there is some more steps.

**Comment by rjchow** [comment]
I've recently added a way to configure the legacy renderer url for opencerts-website, you may use that functionality to point to your branch preview for this repo to do your preview

once your changes have been merged here you will be able to verify certificates on opencerts.io if you have completed the issuer identity steps which is submission to our registry (and/or) DNS-TXT records

**Comment by nikhilranosys** [comment]
Thanks for the response. I tried the solution as per latest changes but getting error.

After running `npm run start` on legacy renderer when I run `npm run start:local` on opencerts website (after taking pull from master) I got below error on node console

```
> opencerts-website@2.0.0 start:local D:\Local Disk\New\Desktop\Projects\smu\opencerts\opencerts-website
> LEGACY_RENDERER_URL="http://localhost:3000" next start -p 3001

'LEGACY_RENDERER_URL' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencerts-website@2.0.0 start:local: `LEGACY_RENDERER_URL="http://localhost:3000" next start -p 3001`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencerts-website@2.0.0 start:local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nikhil Gaur\AppData\Roaming\npm-cache\_logs\2019-08-22T03_58_49_148Z-debug.log
```

**Comment by rjchow** [comment]
not on node console, you need to run it on your shell -- i don't have instructions for how to set the environmental variables on windows

**Comment by nikhilranosys** [comment]
I changed `start:local` to below on my windows environment to make it work for me

`"start:local": "set LEGACY_RENDERER_URL=http://localhost:3000 && next start -p 3001 & LEGACY_RENDERER_URL="`

Apart from this I noticed that you are setting environment variable with name `LEGACY_RENDERER_URL` but getting with name `LEGACY_URL` in [next.config.js file](https://github.com/OpenCerts/opencerts-website/pull/407/files#diff-5d0c276360a637d1b787a57760665fbeR28). I changed that as well after that only it work.

**Comment by rjchow** [comment]
thanks nikhil can you see if this suits your needs?

https://github.com/OpenCerts/opencerts-website/pull/408

**Comment by nikhilranosys** [comment]
Yes, this too worked.

**Comment by rjchow** [comment]
thanks, merged
