### ISSUE TITLE
Pull request with ROPSTEN store address

### ISSUE THREAD

**Issue by nikhilranosys** [OpenCerts/legacy-templates#21]
Our users want to include pull request process also in testing phase so that we will not get surprises at the end when we are ready to go live. 

So is it possible to merge our PR with ROPSTEN Test store address and when we are ready to go to production we will add production store address and generate new PR. Please confirm.

**Comment by rjchow** [comment]
Is this for a SSG accredited institution? If it is we can do it provided they have submitted the form for the registry.

If it's not an SSG accredited institution they will have to use the DNS-TXT verification method

**Comment by nikhilranosys** [comment]
Yes, this is for SSG accredited institute Singapore Management University and they have filled the form for the registry.

**Comment by rjchow** [comment]
yup sure we can do it
