### ISSUE TITLE
link displayed blank page

### ISSUE THREAD

**Issue by seab-gov** [OpenCerts/legacy-templates#33]
Hi, 

1) Why below link displayed blank page ?
https://deploy-preview-32--vigilant-newton-0ec838.netlify.com/

2) Is there any URL for end-user to test the changes before merge to Prod?

**Comment by Nebulis** [comment]
Hi,

1. This repository is supposed to be run in an iframe, and the host component supposed to pass down the document to render. There is nothing to display as such that's why it's a blank page.

2. No prod url. You can test it following https://github.com/OpenCerts/legacy-templates#development

**Comment by Nebulis** [comment]
Note that we are aware of the problem and already opened an issue => https://github.com/OpenCerts/legacy-templates/issues/23
