### ISSUE TITLE
error to view the legacy template

### ISSUE THREAD

**Issue by CITAcadAppsSupport** [OpenCerts/legacy-templates#41]
Hi,

I have tested below scenario:

"Run this legacy-templates repository using npm run dev and keep it running, then run the opencerts-website repository concurrently with the npm run start:local command. You can then preview rendering using the usual OpenCerts.io UI at http://localhost:3001."

able to run http://localhost:3001 but when i tried to view my template, it gave me errors, this also happen on my previous issued certificate.

attached log and json file.
![error_bind](https://user-images.githubusercontent.com/50308837/67445541-e3fea600-f63f-11e9-8052-eace85f6adfc.png)
[localhost-1571879355544.log](https://github.com/OpenCerts/legacy-templates/files/3765243/localhost-1571879355544.log)
[SITCerts_PC1_00000008_1.txt](https://github.com/OpenCerts/legacy-templates/files/3765244/SITCerts_PC1_00000008_1.txt)

ps: we have created new templates and no issue on old project.
opencerts-website-master\src\components\CertificateTemplates\tlds\sg\edu\singaporetech

regards,

**Comment by Nebulis** [comment]
Hi,

$template in your cert is not valid, please follow v2 spec

**Comment by CITAcadAppsSupport** [comment]
Hi,

but our old cert still using this version and our incoming template still using v1.4 (will commit estimate on early nov)

currently i am able to view using the old project:
opencerts-website-master\src\components\CertificateTemplates\tlds\sg\edu\singaporetech

does that mean i am only able to view at my local but still able to commit to production?

regards,

**Comment by rjchow** [comment]
Sorry there's a miscommunication, you're in the registry so you may continue to add templates to legacy-templates for the time being.

Can you point us to the branch with the code that you're having this error with? That'll be easier for us to troubleshoot.

**Comment by CITAcadAppsSupport** [comment]
Hi,

i am using both latest branch on : 
OpenCerts/legacy-templates
OpenCerts/opencerts-website

and perform below: 
"Run this legacy-templates repository using npm run dev and keep it running, then run the opencerts-website repository concurrently with the npm run start:local command. You can then preview rendering using the usual OpenCerts.io UI at http://localhost:3001."

with viewing attached opencert file.
[SITCerts_PC1_00000008_1.txt](https://github.com/OpenCerts/legacy-templates/files/3765926/SITCerts_PC1_00000008_1.txt)
[localhost-1571879355544.log](https://github.com/OpenCerts/legacy-templates/files/3765927/localhost-1571879355544.log)

regards,

**Comment by rjchow** [comment]
I need to look at your code

**Comment by CITAcadAppsSupport** [comment]
i have not added anything, no code change yet

**Comment by Nebulis** [comment]
I just tried and I didn't face any issue

**Comment by CITAcadAppsSupport** [comment]
Hi Both, 

thanks alot for your time, i found the issue on index.js MultiCertificateRenderer part.

i did replaced that folder to our working template....

thanks again.
