### ISSUE TITLE
Travis CI issue

### ISSUE THREAD

**Issue by mmysgp** [OpenCerts/legacy-templates#49]
Job 158.1 finished in a minute. But it seems stuck, cannot move to 158.2.

![image](https://user-images.githubusercontent.com/36496605/68833272-09864900-06ee-11ea-9b2b-f4db11f8058c.png)

![image](https://user-images.githubusercontent.com/36496605/68833283-13a84780-06ee-11ea-949d-699984ae7fb8.png)

**Comment by rjchow** [comment]
Looks like it's completed by now, probably just a bit of slowness
