### ISSUE TITLE
build aborted when running lint fix

### ISSUE THREAD

**Issue by mmysgp** [OpenCerts/legacy-templates#53]
Please refer to the following pull request https://github.com/OpenCerts/legacy-templates/pull/52
The process stuck when running lint fix.  Please help.
Build #179
Job #179.1

![image](https://user-images.githubusercontent.com/36496605/69652190-38b49700-10ac-11ea-98e1-f6d9e007ed87.png)

**Comment by Nebulis** [comment]
Did you try to run it locally?

**Comment by mmysgp** [comment]
The same issue. However, It seems to be due to the overall setting of the project. 
We are not allowed to modify it except our own viewer folder.
Would you please advise the change and fix it in the project level?

**Comment by mmysgp** [comment]
FYI. I encountered the same issue using the master copy without any changes.
> git clone https://github.com/OpenCerts/legacy-templates.git

**Comment by Nebulis** [comment]
I ran lint on master it's fine. I ran it on your MR something is blocking.

Weirdly
```
❯ npx eslint ./src/components/CertificateTemplates/tlds/sg/edu/np --ext .js --max-warnings 0 --debug
```

produces

```
  eslint:cli-engine Linting complete in: 8288ms +32ms
```

I guess something is wrong with one of your file, I leave it to you to investigate on this

**Comment by mmysgp** [comment]
Noticed that eslint cannot fix variables with long values, resulting in process hang.
![image](https://user-images.githubusercontent.com/36496605/69703891-5d9d1e80-112d-11ea-919c-d7a2a0e9b503.png)

The issue was resolved after manually fixed the format. 
![image](https://user-images.githubusercontent.com/36496605/69704075-ba003e00-112d-11ea-9658-ccb6dd42787f.png)
