### ISSUE TITLE
Watermark is not showing when printing

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/legacy-templates#64]
Created a PR recently to add watermark. Please expedite the merge. Thanks.

**Comment by Nebulis** [comment]
To add watermark ? There is already a watermark in this repository. Is it not working ?

**Comment by Nebulis** [comment]
![image](https://user-images.githubusercontent.com/503185/70684832-750a0900-1ce2-11ea-9d3f-0a583f87be49.png)

**Comment by ccewuz** [comment]
not this watermark, but the one only visible upon printing and preview.

**Comment by ccewuz** [comment]
hmmm. tried again with chrom which can show this sloped water mark. but it does not work with firefox.

**Comment by Nebulis** [comment]
Did you enable background graphics in Firefox?

**Comment by ccewuz** [comment]
I see. Yes, once the option is selected I am able to see the watermark on preview. However, we still want to implement our own watermark, for two reasons:

1) Default one has too small fonts
2) By default printing background is off, so users may not know this function. And if they know about it, they can bypass it, which is not desired.

**Comment by Nebulis** [comment]
I get your point. I would like to check with SSG first on this because there are few things that want to raise to them regarding the print

- Would you like to have only your watermark, or is it ok to also display the default one ? (current behaviour display your watermark and the default one)
- On a side note anyone can still investigate the DOM and remove the part corresponding to the watermark
- Just for information, using decentralized-renderer you have complete control over the watermark

**Comment by ccewuz** [comment]
Please see my comments below:

> I get your point. I would like to check with SSG first on this because there are few things that want to raise to them regarding the print. (I can merge tmr as well, but I will still raise the thing to SSG)
[Me: thanks! BTW, just pushed something more which has passed the checks.]
 
>     * Would you like to have only your watermark, or is it ok to also display the default one ? (current behaviour display your watermark and the default one)
[Me: we are ok to display both.]
 
>     * On a side note anyone can still investigate the DOM and remove the part corresponding to the watermark
[Me: yes we are aware. This is the dark side of HTML/JS.]

>     * Just for information, using decentralized-renderer you have complete control over the watermark
[Me: we will move to 2.0 asap.]

**Comment by Nebulis** [comment]
I just merged. I will meet SSG Tuesday, will keep you informed of the discussion, so leaving this MR opened.

Feel free if you have any questions regarding decentralized-renderer

**Comment by ccewuz** [comment]
Noted with thanks!

**Comment by Nebulis** [comment]
So I explained the issue to SSG, current plan is :

> To implement https://github.com/OpenCerts/opencerts-website/pull/462
> 
> - To document about the print function on renderer (docs.opencerts.io)
> - To explore the idea below
> 
> Ideas:
> 
> To remove the print button, use the download that generates (??) a image / pdf of the document
> => delegate to the renderer
> => what about url sharing ?

It's very raw, but it's a general idea. I will work on the first point the coming month.

I'm closing the issue as the initial problem has been solved. Feel free to reopen for discussion if you need it
