### ISSUE TITLE
Error "Default certificate is rendered correctly" in The Travis CI build

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/legacy-templates#68]
Hi, 

Created a new PR as we need to add more templates, but got said error during check. All our own templates have passed, this seems a default certificate. Please look into it. Thanks

![image](https://user-images.githubusercontent.com/47135828/71392898-dddb7480-2644-11ea-8a28-2034b760c960.png)

**Comment by Nebulis** [comment]
Looks like unpkg having christmas troubles => https://github.com/mjackson/unpkg/issues/237

Let's wait a bit

**Comment by ccewuz** [comment]
Looks this has been solved? Can help me rerun integration?
