### ISSUE TITLE
Failure in new PR

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/legacy-templates#80]
Hi, Create a new PR to merge some changes. But it failed at Merge branch 'master' into nus-templates-new (adfeb1d). May I know what's wrong?

**Comment by Nebulis** [comment]
You should be able to see whats wrong by following

![image](https://user-images.githubusercontent.com/503185/80583101-5cf11700-8a42-11ea-8901-18c59b905e65.png)

leading to => https://travis-ci.org/github/OpenCerts/legacy-templates/jobs/680927077

Looks like a linting problem (I didnt check the code)

**Comment by ccewuz** [comment]
Yeah, you are right. An unexpected mistake. thank you!
