### ISSUE TITLE
CI Error:  Frameless Viewer - Default certificate is rendered correctly is failing

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/legacy-templates#81]
Now the error is at:

Frameless Viewer

 ✖ Default certificate is rendered correctly

Can you take a look?

**Comment by Nebulis** [comment]
Fixed by rerunning, keeping this open just in case :)

**Comment by ccewuz** [comment]
thanks

**Comment by ccewuz** [comment]
Hi, the same error relapsed. Can you please look into it?

**Comment by Nebulis** [comment]
```
Frameless Viewer
 ✖ Default certificate is rendered correctly
```

**Comment by Nebulis** [comment]
Should be fixed, could u rebase your mr and retry :)
