### ISSUE TITLE
npm run integration failed

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/legacy-templates#9]
Hi, Looks the integration failed for all templates. For example, with govtech demo error is like below. Anything wrong? 

Frameless Viewer
 × Govtech Demo certificate is rendered correctly

   1) An error occurred in eval code:

      TypeError: Cannot read property 'renderDocument' of undefined

      Browser: Chrome 75.0.3770 / Windows 10.0.0

         19 |test("Govtech Demo certificate is rendered correctly", async t => {
         20 |  // Inject javascript and execute window.opencerts.renderDocument
         21 |  const certificateContent = getData(
         22 |    JSON.parse(readFileSync(join(__dirname, Certificate)).toString())
         23 |  );
       > 24 |  await t.eval(() => window.opencerts.renderDocument(certificateContent), {
         25 |    dependencies: { certificateContent }
         26 |  });
         27 |
         28 |  // Check content of window.opencerts.templates
         29 |  await t.wait(500);

         at eval (c:\data\personal\jobs\EIS\ISIS\RT223084 OpenCerts Project - Integration with
      EduRec\_js\legacy-templates\src\components\CertificateTemplates\tlds\sg\gov\tech\Govtech-Demo-Cert\integration.spec.js:24:11)
         at step (c:\data\personal\jobs\EIS\ISIS\RT223084 OpenCerts Project - Integration with
      EduRec\_js\legacy-templates\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (c:\data\personal\jobs\EIS\ISIS\RT223084 OpenCerts Project - Integration with
      EduRec\_js\legacy-templates\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14)
         at new F (c:\data\personal\jobs\EIS\ISIS\RT223084 OpenCerts Project - Integration with
      EduRec\_js\legacy-templates\node_modules\core-js\library\modules\_export.js:36:28)
         at <anonymous> (c:\data\personal\jobs\EIS\ISIS\RT223084 OpenCerts Project - Integration with
      EduRec\_js\legacy-templates\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
         at test (c:\data\personal\jobs\EIS\ISIS\RT223084 OpenCerts Project - Integration with
      EduRec\_js\legacy-templates\src\components\CertificateTemplates\tlds\sg\gov\tech\Govtech-Demo-Cert\integration.spec.js:19:1)
         at markeredfn (c:\data\personal\jobs\EIS\ISIS\RT223084 OpenCerts Project - Integration with
      EduRec\_js\legacy-templates\node_modules\testcafe\src\api\wrap-test-function.js:17:28)
         at step (c:\data\personal\jobs\EIS\ISIS\RT223084 OpenCerts Project - Integration with
      EduRec\_js\legacy-templates\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (c:\data\personal\jobs\EIS\ISIS\RT223084 OpenCerts Project - Integration with
      EduRec\_js\legacy-templates\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14)
         at new F (c:\data\personal\jobs\EIS\ISIS\RT223084 OpenCerts Project - Integration with
      EduRec\_js\legacy-templates\node_modules\core-js\library\modules\_export.js:36:28)

 1/1 failed (27s)

**Comment by samuellye98** [comment]
Hi, could you try running `npm rebuild node-sass` in the terminal before running `npm run integration`?

**Comment by ccewuz** [comment]
Tried but the error persists.

`npm rebuild node-sass` looks successful as result shows "Binary is fine".

`npm run test` passes.

**Comment by samuellye98** [comment]
Hi, did you run `npm run dev` before running `npm run integration`. There needs to be a server on localhost:3000 in order for the integration tests to work.

**Comment by ccewuz** [comment]
Certainly. I managed to see all my templates rendered correctly in index.html before running integration scripts. Below is a sample. I did some changes to display all templates w/o copying and pasting the JSON content.

![image](https://user-images.githubusercontent.com/47135828/62440843-6c2d8780-b784-11e9-8916-dbb1fba9cfbd.png)

**Comment by samuellye98** [comment]
Could you commit this branch to a new repository on your own Github and we will git clone it and see what's wrong

**Comment by samuellye98** [comment]
Hi, it seems that your certificate is failing the integration tests on Travis CI - https://travis-ci.org/OpenCerts/legacy-templates/jobs/567789663

Try fixing that and see if the travis CI test passes

**Comment by ccewuz** [comment]
Ok, fixed. All checks pass now, including integration test. But locally it still fails. Strange!

**Comment by ccewuz** [comment]
Any update on this? 

Also, I have created a pull request which passed all checks. Can you help merge it?

**Comment by rjchow** [comment]
have responded with some comments
