### ISSUE TITLE
The client Render Test does not work

### ISSUE THREAD

**Issue by mmysgp** [OpenCerts/legacy-templates#95]
Previously we can verify OpenCerts locally before make any change.
Now no response when clicking "Render Certificate" with the default code.

![image](https://user-images.githubusercontent.com/36496605/85650032-2d275e00-b6d7-11ea-8873-474edf9ea034.png)

**Comment by Nebulis** [comment]
Any error in the chrome console?

**Comment by mmysgp** [comment]
Here is the error:

![image](https://user-images.githubusercontent.com/36496605/85695049-41d11980-b70a-11ea-8f98-e84a19e3fd24.png)

**Comment by Nebulis** [comment]
That's not an error, just chrome warning (errors are in red)

I think I know the reason which happened previously with integration test => https://github.com/OpenCerts/legacy-templates/commit/44cb8b3123b94cd69a58c60450d08cde15cbfea1

I didn't dig but it looks like penpan v4 and v5 are not compatible and I see in test/index.html that there is no pinned version of penpal, so it will resolve to the latest available>

You can try to change to `https://unpkg.com/penpal@4.1.1/dist/penpal.min.js` and see if it works for you

**Comment by mmysgp** [comment]
It works after chaning the URL
Suggest to update the url in the master branch.
Thanks.

**Comment by Nebulis** [comment]
Yup will do tmr
